#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5

bspc config top_padding        24
bspc config bottom_padding     0
bspc config left_padding       0
bspc config right_padding      0
bspc config border_width       2
bspc config window_gap         15

exec compfy -b &
exec ~/.config/polybar/launch.sh &
# xidlehook --not-when-audio --not-when-fullscreen --timer 1800 'systemctl suspend' '' &
exec nitrogen --restore &
exec flameshot &
exec nm-applet &
exec setxkbmap -layout us,ru -option 'grp:alt_shift_toggle' &
exec spotifyd --config-path ~/.config/spotifyd/spotifyd.conf &

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color "#8fc1dc"
bspc config focused_border_color "#d3869b"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
# For exercise:
bspc rule -a hello.ui.fx.HelloApp state=floating
bspc rule -a be.ti.howest.jbamaflex.ui.gui.FxProgram state=floating
bspc rule -a be.howest.ti.ui.GUI state=floating
